### ISSUE TITLE
Trigger attacks in simulator and detection

### ISSUE THREAD

**Issue by axoaxel** [DependableSystemsLab/stealthy-attacks#1]
Hi, thanks for sharing the artifact of your ACSAC contribution. 

I was trying to reproduce your attacks in ardupilot SITL. I am using "ardupilot-attack-version", and I have loaded/started mission_1.txt as explained in the instructions (both locally and with the docker instance).

I have two questions:
1) how can I trigger attacks? for example, false data injection.
2) how can I verify that attacks remain stealthy w.r.t. Control Invariants and EKF detectors? are those detectors implemented in the repository?

Thanks,
Alessandro

**Comment by dashpritam** [comment]
Hi, Thanks for your interest in our ACSAC'19 paper. When you start a mission (we have provided mission_1.txt which sets the mission coordinates) you should see the attack is launched after the drone takes off and starts navigating towards the destination. Alternatively, you can modify the attack code (annotated with False Data Injection) in libraries/AC_AttitudeControl/PosControl.cpp.
We implemented CI and EKF detectors in Matlab, derived the possible threshold, and selected the values of false data to be injected in order to remain stealthy.

**Comment by ElaineYao** [comment]
Hi,

In `libraries/AC_AttitudeControl/PosControl.cpp`, do I need to change the value of `falsedata` or the value of `falsedata` is decided by the program?

Thanks,

**Comment by ElaineYao** [comment]
Hi,

In addition, if the user wants to launch attacks at other mode transitions in _Switch Mode_ attack, what should he do? Thanks,

**Comment by dashpritam** [comment]
The value of `falsedata` is selected to remain undetected when triggering attacks. You may change the value of `falsedata` depending on the attack you plan to trigger.
